### ISSUE TITLE
requesting friendlist error

### ISSUE THREAD

**Issue by Yuweisha** [paulov-t/SIT.Core#215]
[ClientRequest] /client/friend/list
getFriendsList
TypeError: Cannot read properties of undefined (reading 'Level')
TypeError: Cannot read properties of undefined (reading 'Level')
    at Mod.getFriendsForUser (D:\EFT\ServerNewNew\user\mods\SIT.Aki-Server-Mod-master\src\mod.js:497:63)
    at Mod.getFriendsList (D:\EFT\ServerNewNew\user\mods\SIT.Aki-Server-Mod-master\src\mod.js:474:30)
    at DialogueController.result.getFriendList (D:\EFT\ServerNewNew\user\mods\SIT.Aki-Server-Mod-master\src\mod.js:393:29)
    at DialogueCallbacks.getFriendList (C:\snapshot\project\obj\callbacks\DialogueCallbacks.js)
    at RouteAction.action (C:\snapshot\project\obj\routers\static\DialogStaticRouter.js)
    at DialogStaticRouter.handleStatic (C:\snapshot\project\obj\di\Router.js)
    at HttpRouter.handleRoute (C:\snapshot\project\obj\routers\HttpRouter.js)
    at HttpRouter.getResponse (C:\snapshot\project\obj\routers\HttpRouter.js)
    at AkiHttpListener.getResponse (C:\snapshot\project\obj\servers\http\AkiHttpListener.js)
    at IncomingMessage.<anonymous> (D:\EFT\ServerNewNew\user\mods\SIT.Aki-Server-Mod-master\src\mod.js:565:49)
TypeError: Cannot read properties of undefined (reading 'Level')
TypeError: Cannot read properties of undefined (reading 'Level')
    at Mod.getFriendsForUser (D:\EFT\ServerNewNew\user\mods\SIT.Aki-Server-Mod-master\src\mod.js:497:63)
    at Mod.getFriendsList (D:\EFT\ServerNewNew\user\mods\SIT.Aki-Server-Mod-master\src\mod.js:474:30)
    at DialogueController.result.getFriendList (D:\EFT\ServerNewNew\user\mods\SIT.Aki-Server-Mod-master\src\mod.js:393:29)
    at DialogueCallbacks.getFriendList (C:\snapshot\project\obj\callbacks\DialogueCallbacks.js)
    at RouteAction.action (C:\snapshot\project\obj\routers\static\DialogStaticRouter.js)
    at DialogStaticRouter.handleStatic (C:\snapshot\project\obj\di\Router.js)
    at HttpRouter.handleRoute (C:\snapshot\project\obj\routers\HttpRouter.js)
    at HttpRouter.getResponse (C:\snapshot\project\obj\routers\HttpRouter.js)
    at AkiHttpListener.getResponse (C:\snapshot\project\obj\servers\http\AkiHttpListener.js)
    at IncomingMessage.<anonymous> (D:\EFT\ServerNewNew\user\mods\SIT.Aki-Server-Mod-master\src\mod.js:565:49)

**Comment by Yuweisha** [comment]
[log_2023.06.20_15-52-36_0.13.0.5.23399.zip](https://github.com/paulov-t/SIT.Core/files/11803430/log_2023.06.20_15-52-36_0.13.0.5.23399.zip)
Those a all log when running server,including BepInEx,EFT Client,Aki
Anyway,during running,my friend joind me as client,i can see him,he cant see me,but i opening door or kill ai,he also can see these change,and body.

**Comment by Lega955** [comment]
I had the requesting friendlist error too, it was a broken profile i had to create a new one
