### ISSUE TITLE
SIT CORE UP?

### ISSUE THREAD

**Issue by RaidmaxSpace** [paulov-t/SIT.Core#28]
when i update the SIT Core via the launcher (the option PRET RELEASE), i have the ping and the RTT stable it's perfect, and with the spawn of the bots control that i finally found :) it's great, but we can't jump with the character, nor this lying, and we can't die nor the bots, we are all invincible

I wonder if I did something wrong?

**Comment by ChewieDM** [comment]
Is your SIT Server Mod updated? You may have this issues with latest Core release without updating the server mod

**Comment by RaidmaxSpace** [comment]
> Is your `SIT Server Mod` updated? You may have this issues with latest Core release without updating the server mod, download the latest [Server Mod](https://github.com/paulov-t/SIT.Aki-Server-Mod)

Good morning,

indeed there is an update of the coop mod,

except that at the start of the server I have a fatal error

ModLoader: Chargement de 1 mods...
Mod SIT Coop version 1.0.0 par Paulov chargé
The application had a critical error and failed to run
Exception produced: Error: Cannot find module 'ws'
Require stack:
- E:\SITCOOP\Server\user\mods\SIT.Aki-Server-Mod-master\src\WebSocketHandler.js
- E:\SITCOOP\Server\user\mods\SIT.Aki-Server-Mod-master\src\mod.js
- C:\snapshot\project\obj\loaders\PreAkiModLoader.js
- C:\snapshot\project\obj\controllers\GameController.js
- C:\snapshot\project\obj\callbacks\GameCallbacks.js
- C:\snapshot\project\obj\di\Container.js
- C:\snapshot\project\obj\Program.js
- C:\snapshot\project\obj\ide\ReleaseEntry.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.

Stacktrace:
 Error: Cannot find module 'ws'
Require stack:
- E:\SITCOOP\Server\user\mods\SIT.Aki-Server-Mod-master\src\WebSocketHandler.js
- E:\SITCOOP\Server\user\mods\SIT.Aki-Server-Mod-master\src\mod.js
- C:\snapshot\project\obj\loaders\PreAkiModLoader.js
- C:\snapshot\project\obj\controllers\GameController.js
- C:\snapshot\project\obj\callbacks\GameCallbacks.js
- C:\snapshot\project\obj\di\Container.js
- C:\snapshot\project\obj\Program.js
- C:\snapshot\project\obj\ide\ReleaseEntry.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1855:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (E:\SITCOOP\Server\user\mods\SIT.Aki-Server-Mod-master\src\WebSocketHandler.js:7:30)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._compile (pkg/prelude/bootstrap.js:1894:32)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)

**Comment by ChewieDM** [comment]
Well, at the moment I wrote the previous comment, I was talking about [this version](https://github.com/paulov-t/SIT.Aki-Server-Mod/tree/a7ca896e1eaf9ec8d5d21fc6a78a6893b2e86d56) that is working for me. Shortly after my comment, there was a update to the mod, and shortly after this comment we also have a update again.

**Comment by Nogway** [comment]
By the way, if you want the actual version to work on you computer you just have to install Node.js and NPM.
open cmd and run the command "npm install ws"
go to C:\Users\{user}\node_modules and copy the "ws" folder
Inside the server folder\user\mod\SITCoop\src create a folder named "node_modules" and paste the folder "ws" inside.

**Comment by RaidmaxSpace** [comment]
OMG

I'm actually missing the "ws" folder.

Thank you <3
